# Generated by Django 6.1.1 on 2026-09-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="poster_url",
            field=models.URLField(blank=True),
        ),
    ]
